### ISSUE TITLE
Can't execute snippet

### ISSUE THREAD

**Issue by ruiborgespaninho** [elephantly/atom-symfony#1]
Hello,

I can't get the list of snippets when I type "sf". Can u tell me how to do this pls ? I'm using Atom 1.16.0

Thanks

**Comment by PurpleBabar** [comment]
Hi :)

Everything works fine with my install, i just type 'sf' in a php file and i do get a list of snippets available, could you tell me a little bit more so that i can reproduce this bug ?

Thx :)

**Comment by ruiborgespaninho** [comment]
Hello,

You point me on the right direction. Indeed, I was trying to type "sf" in a php file but "<?php ?>" was missing !

Thank you

**Comment by PurpleBabar** [comment]
Glad i could help you :)
